### ISSUE TITLE
IBM i - Cannot find module - java/build/Release/nodejavabridge_bindings.node

### ISSUE THREAD

**Issue by krisbaehr** [tryggingamidstodin/node-jt400#11]
I'm trying to install and run this on an IBM i. After what appears to be a successful installation, I try running the script and the below error is thrown.

**Install Log:**

npm install node-jt400 --javahome=$JAVA_HOME
 [K [?25h            [27m [90m... [0m] - build:flushwritable:  [34;40mverb [0m  [35mlinkMans [0m flushwritable@1.0.0 [K[K
> java@0.8.0 install /home/someone/node/projects/remote_users/node_modules/node-jt400/node_modules/java
> node-gyp rebuild

gmake: Entering directory `/home/someone/node/projects/remote_users/node_modules/node-jt400/node_modules/java/build'
gmake: Nothing to be done for `all'.
gmake: Leaving directory `/home/someone/node/projects/remote_users/node_modules/node-jt400/node_modules/java/build'

> java@0.8.0 postinstall /home/someone/node/projects/remote_users/node_modules/node-jt400/node_modules/java
> node postInstall.js
remote_users@0.0.0 /home/someone/node/projects/remote_users
`--  [40m [33mnode-jt400@1.5.4 [39m [49m
  +--  [40m [33mflushwritable@1.0.0 [39m [49m
  +--  [40m [33mjava@0.8.0 [39m [49m
  | +--  [40m [33masync@2.0.1 [39m [49m
  | +--  [40m [33mfind-java-home@0.1.3 [39m [49m
  | +--  [40m [33mglob@7.1.1 [39m [49m
  | +--  [40m [33mlodash@4.16.4 [39m [49m
  | `--  [40m [33mnan@2.4.0 [39m [49m
  +--  [40m [33mJSONStream@1.0.7 [39m [49m
  | +--  [40m [33mjsonparse@1.3.1 [39m [49m
  | `--  [40m [33mthrough@2.3.8 [39m [49m
  `--  [40m [33mq@1.4.1 [39m [49m

**Runtime Error:**

Error: Cannot find module '/home/someone/node/projects/remote_users/node_modules/node-jt400/node_modules/java/build/Release/nodejavabridge_bindings.node'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/someone/node/projects/remote_users/node_modules/node-jt400/node_modules/java/lib/nodeJavaBridge.js:21:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by bergur** [comment]
Hello @krisbaehr my name is Bergur and I work at tryggindamidstodin. Sorry for the late reply.

This seems to be a problem with the node-java module wehn installed on a windows machine. Have you checked the readme on windows installation? https://github.com/joeferner/node-java
It's probably some path issue to JVM.

You could also tro to isolate the error by making a new folder / clean directory and do something like

```
npm init
npm install node-java --save
```
End then running some example code
```
var java = require('java');
var charArray = java.newArray("char", "hello world\n".split(''));
```

**Comment by bergur** [comment]
I am closing this ussue since no reply or comment has been made.
