### ISSUE TITLE
Problem using module

### ISSUE THREAD

**Issue by MSilvaPT** [tryggingamidstodin/node-jt400#13]
I've tried to use the module several times and ways and every time i get the same error when access to pool function

> Error: Could not create class nodejt400.JT400
java.lang.NoClassDefFoundError: nodejt400/JT400
Caused by: java.lang.ClassNotFoundException: nodejt400.JT400
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)

The code that i'm actually using is:

`    const config = {
        host: 'HOST',
        user: 'USER',
        password: 'PASS'
    };`
    `var as400 = require('node-jt400');`
    `var pool = as400.pool(config);`
    `debug("Conn Ret: %O", pool);`

Already installed JDK and JRE version 1.7 and checked versions from java and javac...

Could you please give me some help?

Cheers,
MSilvaPT

**Comment by bergur** [comment]
Hi MSilvaPT and sorry for the late reply.

Did you get any errors while doing npm install?
On what operation system are you running?

**Comment by MSilvaPT** [comment]
Hello @bergur thanks for the support!

I'm running the project on Windows 10 and yesterday i've tried to run the same code in a linux machine and run without any problem! So, for shure it will be a problem of compatibility with windows platforms... :(

Doing npm install on windows machine give me this result:
>npm WARN as400api@1.0.0 No repository field.
>npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
>npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: >wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

I think that these warning don't have any relation with the problem...

**Comment by bergur** [comment]
Hi again.

If it works on linux but not on windows it's most likely a problem with node-java.
https://github.com/joeferner/node-java

If you create a "dummy-project" in another folder with

```
npm init
npm install java --save

var java = require('java');
var charArray = java.newArray("char", "hello world\n".split(''));
```

And then run this code, do you get any errors?

If you get any errors I would reccomend going through the readme for node-java and get this code-snippet running.

**Comment by MSilvaPT** [comment]
Hello,

I've tried that and runs without any error. So the java module is running OK i guess...

This is very extrange to me because everything point to java module but in the end the module works ok...

Thanks for the help

**Comment by bergur** [comment]
Hi @MSilvaPT 

Sorry for the late reply, did you ever found a solution to your problem?

**Comment by MSilvaPT** [comment]
I've found the problem... Seems like having different java versions in the system and the module gets confused. After uninstall all the versions and keep only one, the module starts running!
