### ISSUE TITLE
Can the docs be more detailed?

### ISSUE THREAD

**Issue by Hyurl** [tryggingamidstodin/node-jt400#14]
e.g. configuration properties?

**Comment by crimsonhawk009** [comment]
Should be able to use any of the properties from [here](https://www.ibm.com/support/knowledgecenter/en/ssw_ibm_i_73/rzahh/javadoc/com/ibm/as400/access/doc-files/JDBCProperties.html).

I specify them like so.
```node
const jt400 = {
	host: 'hostname',
	user: 'user',
	password: 'supersecretpassword',
	naming: 'sql',
	libraries: 'QGPL',
	trace: 'false',
	'translate binary': 'true',
};
```

**Comment by Hyurl** [comment]
Thanks, I just checked it out, but still got some questions, the docs says those properties don't include DataSource properties, e.g. the `host` you just showed, I can't find them on the website, would it be possible to list them out or tell me the URL that introduces them, please.

**Comment by crimsonhawk009** [comment]
Well `host` is an internal property that gets referenced by the JDBC URL.

https://github.com/tryggingamidstodin/node-jt400/blob/ede0b7d2c42375820419638ef020691f5def7fcb/java/src/nodejt400/JT400.java#L144

This should get you what you need from IBMs Knowledge Center, [Driver Connection Properties.](https://www.ibm.com/support/knowledgecenter/ssw_ibm_i_73/rzaha/conprop.htm).

**Comment by Hyurl** [comment]
Thank you, it helps a lot.
