### ISSUE TITLE
Select from VIEW

### ISSUE THREAD

**Issue by akilinomendez** [tryggingamidstodin/node-jt400#16]
This package is very good, run perfect.

But When I want to make a select from a view "[SQL0204] FROM in * LIBL of type * FILE not found" and if I want to specify the schema of the table does not work either

Any solution?

**Comment by crimsonhawk009** [comment]
Need more specifics in what code you are running. I use views all the time and they work fine.

## Example
### Create view statement.
```sql
CREATE VIEW TEST.SYSTABLES AS 
SELECT TABLE_NAME FROM SYSIBM.TABLES WHERE TABLE_SCHEMA LIKE 'SYS%'
```
### Javascript
```javascript
const pool = require('node-jt400').pool(config);
pool.query('SELECT * FROM TEST.SYSTABLES FETCH FIRST 2 ROWS ONLY')
	.then(function (result) {
		console.log('result');
		console.log(result);
	})
	.fail(function (error) {
		console.log('error');
		console.log(error);
	});
```
### Result
```javascript
result
[ { TABLE_NAME: 'AUTHID0001' },
  { TABLE_NAME: 'AUTHORIZATIONS' } ]
```

**Comment by crimsonhawk009** [comment]
Could you try adding naming sql to your config like so?
```javascript
const config = {
	host: 'xxx',
	user: 'xxx',
	password: 'xxx',
	naming: 'sql'
}
```

**Comment by akilinomendez** [comment]
Amazing, it works. Many thanks. It solves many problems

**Comment by bergur** [comment]
Thank you @crimsonhawk009 :)
