### ISSUE TITLE
result is printing the query no the value

### ISSUE THREAD

**Issue by chandravellanki** [tryggingamidstodin/node-jt400#2]
I was following the example code from npmjs.org and used the following query:

```
pool.query('SELECT FDFIL1, FDFIL2, FDFIL3, FDFIL4, FDFIL5, FDFIL6 FROM MYLIB/MYFILE WHERE FDFIL1= ? or WHERE FDFIL1= ?', ['T', ' '])
    .then(function(result) {
        console.log(result[0].FDFIL1);
    })
```
And the console.log prints the entire query and the params requested, not the value that is returned.

Am I missing anything?

**Comment by jakobrun** [comment]
Yes, it is probably an error in the sql statement. You can catch the error with .fail:
pool.query('SELECT FDFIL1, FDFIL2, FDFIL3, FDFIL4, FDFIL5, FDFIL6 FROM MYLIB/MYFILE WHERE FDFIL1= ? or WHERE FDFIL1= ?', ['T', ' '])
    .then(function(result) {
        console.log(result[0].FDFIL1);
    }).fail(function(err) {
         console.log(err.stack);
    });

**Comment by chandravellanki** [comment]
Thank you. This helped.
