### ISSUE TITLE
Column value trimmed

### ISSUE THREAD

**Issue by airicyu** [tryggingamidstodin/node-jt400#22]
I find that the SQL query result values are all trimmed.
But currently there is no way to get untrimmed raw value result with the library.

In order to get raw untrimmed value, you may need to do such changes:
In the java class "JdbcJsonClient.java" 's method "query", replace the line

> json.put(metaData.getColumnLabel(i), trim(rs.getString(i)));

With 

> json.put(metaData.getColumnLabel(i), rs.getString(i));

Suggest to have some library option or in query option to switch the trim.

**Comment by bergur** [comment]
Hi @airicyu thanks for comments.

I'll have to talk to the team about this and get back to you.

**Comment by eduardrock** [comment]
Is this issue already solved?
I have the same problem because I need to get the values of some varchar fields considering the leading and trailing spaces of a text, but unfortunately node jt-400 always trim the texts

**Comment by cwg999** [comment]
No it is not. 

https://github.com/tryggingamidstodin/node-jt400/blob/7eca3875c617e88b0d4f94ca72cf3038dbb50313/java/src/nodejt400/JdbcJsonClient.java#L48

I'm not sure how I feel about "trim" being the default as suggested an option to turn it off would be nice. 

It doesn't appear that queryAsStream does the same. Maybe you could try that?

**Comment by bergur** [comment]
I am looking into this, I can understand the reasoning behind trim not being default, but that would be a breaking change. I will talk the lead-dev about adding a new paramter to the query to turn of trimming and stay in touch.

**Comment by bergur** [comment]
A fix is now available

```javascript
const sql = 'SELECT  name FROM list WHERE id = ?'
const params = 1
const options  = { trim: false }

jt400.query(sql, params, options)
```
