### ISSUE TITLE
Visual popup on bad user or password

### ISSUE THREAD

**Issue by timmo001** [tryggingamidstodin/node-jt400#29]
# Problem

When the username or password is incorrect, a window pops up with an error. I am using a purely [server-side application](https://github.com/timmo001/iseries-api) which cannot rely on a visual popup blocking any further execution.

![image](https://user-images.githubusercontent.com/28114703/47374801-b60e1b00-d6e6-11e8-9f97-b3ebd537edc5.png)

![image](https://user-images.githubusercontent.com/28114703/47374810-befeec80-d6e6-11e8-8c43-620d300f68f7.png)

## Requested changes

Stop the dialog from appearing on bad login credentials

## Usage

```js
const config = { host: req.hostname, user: req.username, password: req.password };
const pool = require('node-jt400').pool(config);
```

**Comment by cwg999** [comment]
Note for development: https://stackoverflow.com/questions/26032662/jt400-jar-disable-login-screen

**Comment by cwg999** [comment]
This can be closed @bergur

**Comment by timmo001** [comment]
Thanks for merging. 👍

**Comment by bergur** [comment]
I tested this today and merged. Closing this issue. Thanks for the help @timmo00 :)
