### ISSUE TITLE
jdbcwritestream file missing

### ISSUE THREAD

**Issue by AdamPBell** [tryggingamidstodin/node-jt400#3]
It appears that the file jdbcwritestream didn't get checked in with the latest commit. 

jt400.js line 5:
```javascript
	createJdbcWriteStream = require('./jdbcwritestream'),

**Comment by jakobrun** [comment]
ups... this is fixed now. Thank you for spotting that.

**Comment by AdamPBell** [comment]
Not a problem. Glad I could help.
