### ISSUE TITLE
Question: Does this library support RPG calls with simple arrays and data structure arrays?

### ISSUE THREAD

**Issue by danny-hcs** [tryggingamidstodin/node-jt400#30]
I see that the code supports structs, but I don't see anything for simple arrays or data structure arrays.  Does this library support either of those for RPG calls?

**Comment by cwg999** [comment]
"RPG calls" --- do you mean calling a program using `.pgm()` ? (Sorry I don't actually deal a lot with RPG or calling programs on the IBM i ) I see a `StructPgmParam` in the code so maybe structure arrays?

Related links: 
https://github.com/tryggingamidstodin/node-jt400/blob/aae49fd308b3d61b33fdbb5c816c489f7821d960/java/src/nodejt400/Pgm.java

https://javadoc.midrange.com/jtopen/com/ibm/as400/access/ProgramCall.html

**Comment by danny-hcs** [comment]
As far as I can tell this is not supported.  I'll have to extend the functionality.  Thanks.

**Comment by jkovalchik** [comment]
@danny-hcs How did you end up handling this? I'm needing to do the same thing you were.
