### ISSUE TITLE
OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by tshma** [tryggingamidstodin/node-jt400#32]
We test node-jt400 for our uses, and are having a problem with big result sets (that is at about 1 million records for a pretty small record size). We get this error:
![error-stack](https://user-images.githubusercontent.com/15185767/49234139-2acc2780-f400-11e8-85e0-c1242f940feb.PNG)

We couldn't find where we can configure the heap space size for the Java process that is ran internally by the node module. Is there a way to set -Xmx somehow?

**Comment by cwg999** [comment]
See (you could edit the code and add in your own configuration) https://github.com/tryggingamidstodin/node-jt400/blob/580d4b7dd4f3953707e2e9bf27292a716ab396a0/lib/jt400.ts#L26

Maybe make a PR request to make this configurable?

**Comment by jakobrun** [comment]
You could also consider using streams when working with big result sets: https://github.com/tryggingamidstodin/node-jt400#sql-stream

**Comment by tshma** [comment]
Thanks! that stream's option might be just what I need

**Comment by bergur** [comment]
Hey @tshma, did you manage use the streams?
