### ISSUE TITLE
Encoding problems with CCSID

### ISSUE THREAD

**Issue by coinnect-project** [tryggingamidstodin/node-jt400#38]
I used jt400 few times in the past in some native java programs and never had this issue. Now I wanted to use nodejs and this package. So i call an as400 program passing json as parameter and getting another json in another parameter as response: problem as400 get the '{' and '[' chars as 'à' and 'è' chars...
As400 is set with 1144 CCSID and I see from logs that my pool config is right

> Toolbox for Java - JDBC 3.0 Open Source Software, JTOpen 9.1, codebase 5770-SS1 V7R3M0.00 built=20160705 @RF
java.home=/opt/jdk1.8.0_201/jre java.vm.vendor=Oracle Corporation java.vm.info=mixed mode java.runtime.version=1.8.0_201-b09 java.fullversion=null java.vm.version=25.201-b09 java.version=1.8.0_201 os.name=Linux os.version=3.10.0-514.2.2.el7.x86_64
lun lug 8 17:51:36:515 CEST 2019  as400@setString: Properties  (1225358173) : package ccsid = "1144".
lun lug 8 17:51:36:521 CEST 2019  as400@setString: Properties  (1225358173) : trace = "true".
lun lug 8 17:51:36:522 CEST 2019  as400@setString: Properties  (1225358173) : naming = "system".

then when connection is established seems that ccsid is also matching:

> lun lug 8 17:51:43:976 CEST 2019  as400: ConnectionPool com.ibm.as400.access.AS400JDBCConnectionPool@6cc9c0a9 (1825161385) : Filling the pool with 1 connections..
lun lug 8 17:51:44:086 CEST 2019  as400@setString: Properties  (1225358173) : metadata source = "1".
lun lug 8 17:51:44:089 CEST 2019  as400: Toolbox for Java - Open Source Software, JTOpen 9.1, codebase 5770-SS1 V7R3M0.00 built=20160705 @RF
lun lug 8 17:51:44:090 CEST 2019  as400: JDBC Level: 40
lun lug 8 17:51:44:091 CEST 2019  as400@setString: Properties  (1225358173) : package ccsid = "1144".
lun lug 8 17:51:44:092 CEST 2019  as400: Connection 192.168.10.250 (1223930207) : Client CCSID = 1144.
lun lug 8 17:51:44:092 CEST 2019  as400: Connection 192.168.10.250 (1223930207) : Setting server NLV = 2932.
lun lug 8 17:51:44:095 CEST 2019  as400: Connection 192.168.10.250 (1223930207) : Client functional level = V7R2M01   .
lun lug 8 17:51:44:095 CEST 2019  as400: Connection 192.168.10.250 (1223930207) : Data compression = RLE.
lun lug 8 17:51:44:095 CEST 2019  as400: Connection 192.168.10.250 (1223930207) : ROWID supported = true.
lun lug 8 17:51:44:095 CEST 2019  as400: Connection 192.168.10.250 (1223930207) : True auto-commit supported = true.
lun lug 8 17:51:44:096 CEST 2019  as400: Connection 192.168.10.250 (1223930207) : 128 byte column names supported = true.
lun lug 8 17:51:44:096 CEST 2019  as400: Connection 192.168.10.250 (1223930207) : 128 length schema names supported = true.
lun lug 8 17:51:44:096 CEST 2019  as400: Connection 192.168.10.250 (1223930207) : Maximum decimal precision = 31.
lun lug 8 17:51:44:096 CEST 2019  as400: Connection 192.168.10.250 (1223930207) : Maximum decimal scale = 31.
lun lug 8 17:51:44:096 CEST 2019  as400: Connection 192.168.10.250 (1223930207) : Minimum divide scale = 0.
lun lug 8 17:51:44:096 CEST 2019  as400: Connection 192.168.10.250 (1223930207) : Translate hex = character.
lun lug 8 17:51:44:096 CEST 2019  as400: Connection 192.168.10.250 (1223930207) : query optimize goal = 0.
lun lug 8 17:51:44:097 CEST 2019  as400: Connection 192.168.10.250 (1223930207) : query storage limit = -1.
lun lug 8 17:51:44:097 CEST 2019  as400: Connection 192.168.10.250 (1223930207) : Using extended datastreams.
lun lug 8 17:51:44:100 CEST 2019  as400: Connection 192.168.10.250 (1223930207) : JDBC driver major version = 11.
lun lug 8 17:51:44:100 CEST 2019  as400: Connection 192.168.10.250 (1223930207) : IBM i VRM = V7R2M0.
lun lug 8 17:51:44:100 CEST 2019  as400: Connection 192.168.10.250 (1223930207) : Server CCSID = 1144.
lun lug 8 17:51:44:100 CEST 2019  as400: Connection 192.168.10.250 (1223930207) : Server functional level = V7R2M00016 (16).
lun lug 8 17:51:44:100 CEST 2019  as400: Connection 192.168.10.250 (1223930207) : Server job identifier = 092323/QUSER/QZDASOINIT.
lun lug 8 17:51:44:101 CEST 2019  as400@setString: Properties  (1225358173) : decimal separator = ".".
lun lug 8 17:51:44:101 CEST 2019  as400@setString: Properties  (1225358173) : date format = "dmy".
lun lug 8 17:51:44:101 CEST 2019  as400@setString: Properties  (1225358173) : date separator = "/".
lun lug 8 17:51:44:101 CEST 2019  as400@setString: Properties  (1225358173) : time format = "hms".
lun lug 8 17:51:44:101 CEST 2019  as400@setString: Properties  (1225358173) : time separator = ":".
lun lug 8 17:51:44:121 CEST 2019  as400: Connection S2120CEW (1223930207)  open.
lun lug 8 17:51:44:121 CEST 2019  as400@setProperties: Connection S2120CEW (1223930207) : Auto commit = "true".
lun lug 8 17:51:44:122 CEST 2019  as400@setProperties: Connection S2120CEW (1223930207) : Read only = "false".
lun lug 8 17:51:44:122 CEST 2019  as400@setProperties: Connection S2120CEW (1223930207) : Transaction isolation = "1".
lun lug 8 17:51:44:122 CEST 2019  as400: ConnectionPoolDataSource  (1203189789) : connection created.

but when i call the program as400 get characters wrong and so do I if i print the response...
on server the 'localectl status' command give 

> System Locale: LANG=it_IT.UTF-8
       VC Keymap: it
      X11 Layout: it

I don't know where the problem could be, I tried many different ccsid in the pool config but results is always the same...
any hint?
thanks

**Comment by cwg999** [comment]
I doubt that the connection would translate program parameters (strings, char[])... but I could be wrong. 
You probably have to send the program the string format it is expecting.

**Comment by coinnect-project** [comment]
> I doubt that the connection would translate program parameters (strings, char[])... but I could be wrong.
> You probably have to send the program the string format it is expecting.
> 
> In C# ... I've had to do things like this for instance, just to give you an example that some languages do provide tools for conversion.
> 
> ```
>                     var ibm = Encoding.GetEncoding("IBM037");
>                     var ascii = Encoding.ASCII;
>                     var convertedString = Encoding.Convert(ibm, ascii, toConvert);
>                     var finalValue = ascii.GetString(convertedString).Trim();
> ```
> 
> Or its ....
> 
> [this line](https://github.com/tryggingamidstodin/node-jt400/blob/a92b312831928680760f9e7af220b32570c5970e/java/src/nodejt400/Pgm.java#L210) 😬
> Note Cp871 refers to EBCDIC: Iceland.
> 
> ```
> // public AS400Text(int length, java.lang.String encoding) 
> parser = new AS400Text(paramDef.getFirstInt("size", "precision"), "Cp871"); 
> ```

I think the Cp871 in the code is the problem. Because it means that iceland encoding is hardcoded into the module and so then I run the program it will translates what as400 responds with that instead of the one my as400 has (Cp1144)....why someone would hardcodes this parameter?? plus the iceland coding! not even a standard or more global one like USA😂
So now how can I fix this fast to test with my cp? I have to download source, rebuild the jt400wrap jar then put it into ../node_modules/node-jt400/java/lib folder? 
Anyway I think it should also fixed for everyone, maybe just using the "package ccsid" pool setting

**Comment by bergur** [comment]
Hi @coinnect-project and thanks for the report, and as per usual thanks @cwg999 for helping us out with this module.

You might be correctt that `parser = new AS400Text(paramDef.getFirstInt("size", "precision"), "Cp871");` is possibly be the problem .

Regarding 

> Why someone would hardcodes this parameter?? plus the iceland coding! not even a standard or more global one like USA

This has a very simple answer: Tryggingamidstodin is an Icelandic insurance company that has legacy AS400 systems. We needed a way for our new nodeJS application to interact with our old systems so we wrote this module purely for inhouse use. It was really never ment as an open-source module. But we decided anyway to put it on our public github (not our inhouse gitlab), just in case it might help other programmers, since AS400 legacy systems are quite common.

Therefore all features and most of the code decisions are based purely on the needs of Tryggingamidstodin. We have tried however to fix these things, as they come up and make it a better open source component, thanks to people like you who come across decisions like this. The same applies with features/functions that are in the JT400 ToolBox but not in this one.

We welcome most additions and are open to pull requests so if you want to fork this and see if changing the icelandic encoding to the ccsid parameter would fix your problem then that would be aswesome. If all tests run, then I will happily merge it with the master.

**Comment by coinnect-project** [comment]
> Hi @coinnect-project and thanks for the report, and as per usual thanks @cwg999 for helping us out with this module.
> 
> You might be correctt that `parser = new AS400Text(paramDef.getFirstInt("size", "precision"), "Cp871");` is possibly be the problem .
> 
> Regarding
> 
> > Why someone would hardcodes this parameter?? plus the iceland coding! not even a standard or more global one like USA
> 
> This has a very simple answer: Tryggingamidstodin is an Icelandic insurance company that has legacy AS400 systems. We needed a way for our new nodeJS application to interact with our old systems so we wrote this module purely for inhouse use. It was really never ment as an open-source module. But we decided anyway to put it on our public github (not our inhouse gitlab), just in case it might help other programmers, since AS400 legacy systems are quite common.
> 
> Therefore all features and most of the code decisions are based purely on the needs of Tryggingamidstodin. We have tried however to fix these things, as they come up and make it a better open source component, thanks to people like you who come across things like this.
> 
> We welcome most additions and are open to pull requests so if you want to fork this and see if changing the icelandic encoding to the ccsid parameter would fix your problem then that would be aswesome. If all tests run, then I will happily merge it with the master.

I fixed the issue...the problem was the hardcoded Cp871 encoding for programs 😉 I created a pull request removing the parameter so it will use the constructor without the encoding parameter, the default locale. For me it works (both with Cp1144 both without the parameter)
