### ISSUE TITLE
EBCDIC to ASCII

### ISSUE THREAD

**Issue by chandravellanki** [tryggingamidstodin/node-jt400#4]
Is there any built-in mechanism to convert EBCDIC to ASCII or UTF? If so please let me know.

**Comment by jakobrun** [comment]
Yes, this is built in to the jt400.jar from IBM. It converts from what ever encoding you are using on the database to what ever encoding you use on the JVM.

**Comment by chandravellanki** [comment]
Ok, so do I have to specify the encoding that I have to use while connecting using the following? if so can you help me with that. The issue that I am facing is, my server is sending me the EBCDIC strings, I was hoping to get ASCII strings.

```
require('node-jt400').pool({
    host: config.host,
    user: config.user,
    password: config.password
});
```

**Comment by jakobrun** [comment]
hmmm... I'm not sure why this is happening. But the connection properties that are currently supported on a pool connection are:
naming, dateFormat, transactionIsolation, sort, sortTable, sortLanguage, libraries
you can read more about it here: https://publib.boulder.ibm.com/iseries/v5r2/ic2924/index.htm?info/rzahh/javadoc/JDBCProperties.html

**Comment by chandravellanki** [comment]
Ok. I found the answer, in my case the server field is defined with CCSID 65535 and if it is 65535 then the translation is not done by jt400 automatically. There is an option called "translate binary" that can be ste to "true" and added to URL while connecting . Any idea how I can set this property during connection? Thank you for your help...

**Comment by chandravellanki** [comment]
For now, I have changed the file to use CCSID 37 and it worked. But it would really help if there is a way to specify "Translate binary" to trure during connection.

**Comment by jakobrun** [comment]
All connection properties are now configurable.

**Comment by cwg999** [comment]
Updated Link:
https://www.ibm.com/support/knowledgecenter/en/ssw_ibm_i_73/rzahh/javadoc/com/ibm/as400/access/doc-files/JDBCProperties.html

Example for connection options in node-jt400:

``
const config = {
  host: host,
  user: username,
  password: password,
  "translate binary": "true"
};
``
