### ISSUE TITLE
Close() function is not included in .ts file

### ISSUE THREAD

**Issue by SK-Commit** [tryggingamidstodin/node-jt400#43]
export interface BaseConnection {
    ...
    close: () => void;
    ...
}

in jt400.d.ts would fix this.

**Comment by bergur** [comment]
Hi @SK-Commit thanks for issue. We will look into this.

**Comment by bergur** [comment]
Hi again @SK-Commit, I've updated the code and published a new version patch.
https://github.com/tryggingamidstodin/node-jt400/blob/fe499c38d49d4eb718f8c0b3bd7762a19e82f706/lib/jt400.ts#L525

Thanks for tip.
