### ISSUE TITLE
Question: How to invoke AS/400 Program with a grouping structure for parameters

### ISSUE THREAD

**Issue by dimitarb-openlegacy** [tryggingamidstodin/node-jt400#49]
Hello,

I am trying to use node-jt400 in order to invoke a program on the AS/400, which has the following structure:
```
       IDENTIFICATION DIVISION.         
       DATA DIVISION.                   
       PROGRAM-ID. CLIENTDET.           
       LINKAGE SECTION.                 
          01 CLIENT-NUM        PIC 9(8).
          01 CLIENT-REC.                
            02 FIRST-NAME     PIC X(16).
            02 LAST_NAME      PIC X(28).
```
The above program receives a Client Number and for it returns the Client Name (first and last).

I am not sure how to define the parameters schema in regards to the CLIENT-REC.
I am using the below code:
```
const myProgram = pool.defineProgram({
    programName: 'CLIENTDET',
    paramsSchema: [
      { type: 'DECIMAL', precision: 8,   scale: 0, name: 'clientNum' },
      { type: 'CHAR'   , precision: 16,  scale: 0, name: 'firstName' },
      { type: 'CHAR'   , precision: 28,  scale: 0, name: 'lastName' }
    ]
});

myProgram(
    {
      clientNum: 3,
      itemName: '',
      lastName: ''
    }
  )
  .then(result => {
    console.log(result)
  }). fail(error => {
      console.log(error)
  });
```
And I am getting the below exception:
`AS400Message (ID: MCH0802 text: Total parameters passed does not match number required.)`

I have tried to invoke the program in the following way also, but did not work either:
```
myProgram(
    {
      clientNum: 3,
      clientRec: {itemName: '',
                   lastName: ''}
    }
  )
  .then(result => {
    console.log(result)
  }). fail(error => {
      console.log(error)
  });
```

Could you please advise how I can define the parameters schema and how I can invoke the program?

Mike.

**Comment by bergur** [comment]
Hi @dimitarb-openlegacy 

If I understand you correctly you should be able to do something like this:

```
const myProgram = pool.defineProgram({
    programName: 'myname',
    paramsSchema: [
      { param1 },
      group1: [
        { group1-param1 },
        { group1-param2 }
      ]
  ]
});
```

and then invoke it:

```
myPogram({
 param1: value,
 group1: {
  group1-param1: value
  group1-param2: value
 }
})
```

So in your case i think it would look like:

```
const myProgram = pool.defineProgram({
    programName: 'CLIENTDET',
    paramsSchema: [
      { type: 'DECIMAL', precision: 8,   scale: 0, name: 'clientNum' },
      clientRec: [
        { type: 'CHAR'   , precision: 16,  scale: 0, name: 'firstName' },
        { type: 'CHAR'   , precision: 28,  scale: 0, name: 'lastName' }
     ]
    ]
});
```

And then to invoke it:

```
myProgram({
  clientNum: 3,
  clientRec: {   
      itemName: '',
      lastName: ''
   }
})
```

**Comment by dimitarb-openlegacy** [comment]
Hello Bergur,

Thanks a lot for your advise!

When I do the proposed description for the paramsSchema (I tried that as part of the second test), I get the below exception:
```
C:\Projects\NodeJS\as400\app.js:18
      clientRec: [
               ^

SyntaxError: Unexpected token :
    at Module._compile (internal/modules/cjs/loader.js:721:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

**Comment by bergur** [comment]
Yeah my bad. The group needs to be inside a object. I've updated my answer above.

**Comment by dimitarb-openlegacy** [comment]
Thanks a lot Bergur!

Now I get the following exception:
```
Tue Dec 17 13:50:15:131 EET 2019  as400: Unknown com.ibm.as400.access.PoolConnectionEventListener@388e85a4 (948864420) : Returning active connection to the pool..
{ [Error: Error running instance method
com.ibm.as400.access.ConnectionDroppedException: Connection was dropped unexpectedly.
        at com.ibm.as400.access.ClientAccessDataStream.construct(ClientAccessDataStream.java:62)
        at com.ibm.as400.access.AS400ThreadedServer.run(AS400ThreadedServer.java:357)
        at java.lang.Thread.run(Thread.java:748)
]
  cause: nodeJava_com_ibm_as400_access_ConnectionDroppedException {} }
```

How I can identify the problem - I have trace enabled, but there is no information for this exception?

Note: I tried to invoke another program, but I got exactly the same problem ...

Thanks again for your support!

**Comment by bergur** [comment]
This message is coming from the IBM Toolbox (the java that's running behind), telling you that it has lost the connection. Have you verified that this connection works? Maybe with a simple query to a database (if you have one)

Your code should look something like

```javascript
const jt400 = require('node-jt400')
const pool = jt400.pool({ config })

pool.myProgram({
  param1: value
}).then(res => {
  console.log(res)
}).catch(err => {
  console.log(err
})
```

**Comment by dimitarb-openlegacy** [comment]
Hi Bergur,

I have verified that this connection works, as I am succeeding to connect and execute the same program using the JT400 jar directly ...

Also, I get the same exception every time I run the Node JS program, so the problem is not caused by an incidental network issue.

I guess that I am not configuring something correctly. Any ideas ... ?

**Comment by cwg999** [comment]
So just to clarify, you can't run _anything_ in node-jt400? Not even a simple SQL query?

**Comment by bergur** [comment]
Hmm no not at the top of my mind. Have you tried anything else with the node module besides programs (maye a sql query).  I'm just wondering if its the config object that's maybe wrong or if its the program call.

**Comment by dimitarb-openlegacy** [comment]
Hello Bergur, CWG999,

I see that the library name is correct, as I checked the path during the previous exceptions that I was getting.

I tried with simple SQL statement as advised:
```
pool.query('SELECT CURRENT SCHEMA AS field1 FROM SYSIBM/SYSDUMMY1')
  .then(result => {
    console.log('result');
    const field1 = result[0].FIELD1;
    console.log(field1);
  })
  .catch(error => {
    console.log('error');
    console.log(error);
  });
```

And I get the below result:
```
result
*LIBL
```

So the connection looks OK ...

**Comment by cwg999** [comment]
In the docs I see

`ATTENTION: In version 3.0 we added a optional timeout parameter for program calls. This defaults to 3 sec. This is a breaking change since your programs will no longer halt or hang for extended period and therefore never give a response. If you have complicated programs that run for longer than 3 sec then you need to adjust the timeout parameter for those specific calls. Setting it to 0 will ignore the timeout limit.`

Have you tried a 0 timeout limit?

**Comment by dimitarb-openlegacy** [comment]
I was using the default timeout - 3 sec.

I tried with 0, but it hangs ...

I tried with 10 and after 10 seconds I get the same exception ...
```
Tue Dec 17 17:01:18:092 EET 2019  as400: Unknown com.ibm.as400.access.PoolConnectionEventListener@388e85a4 (948864420) : Returning active connection to the pool..
{ [Error: Error running instance method
com.ibm.as400.access.ConnectionDroppedException: Connection was dropped unexpectedly.
        at com.ibm.as400.access.ClientAccessDataStream.construct(ClientAccessDataStream.java:62)
        at com.ibm.as400.access.AS400ThreadedServer.run(AS400ThreadedServer.java:357)
        at java.lang.Thread.run(Thread.java:748)
]
  cause: nodeJava_com_ibm_as400_access_ConnectionDroppedException {} }
```

**Comment by cwg999** [comment]
Well, do you think your program(s) are being provided bad data in some format that would cause them to misbehave? Can you try a simple program with simple inputs? Can you log the inputs in your program on the server?

**Comment by bergur** [comment]
Hi  again @dimitarb-openlegacy 

I would lean in the same direction as @cwg999 - the inputs or something else is making the program unresponsive. We've had similiar problems when the data is wrong, the mapping is wrong or the precison and/or scale is wrong.

From the docs:

> The Decimal type maps to com.ibm.as400.access.AS400PackedDecimal The Numeric type maps to com.ibm.as400.access.AS400ZonedDecimal Everything else (char) maps to com.ibm.as400.access.AS400Text. Precision is the size and scale is the decimals.

**Comment by dimitarb-openlegacy** [comment]
Hello Bergur, cwg999,

This was exactly my problem - Packed vs Zoned Decimal. I changed the Decimal to Numeric and I succeeded to invoke the Program and get the result!

Thanks again for your help!

**Comment by bergur** [comment]
Awesome, good to hear.
