### ISSUE TITLE
Error when adding require for node-jt400

### ISSUE THREAD

**Issue by geoffreywk** [tryggingamidstodin/node-jt400#5]
When I add the require to include node-jt400 in my server.js file I get an error when I run in debugger.  When I stop the debugger the output shows the following:

Internal error: TypeError: Cannot read property '0' of undefined
The program '[4060] node.exe' has exited with code -1 (0xffffffff).

Below is all the code I have up to where I declare the require.

var express = require("express");
var app = express();
var bodyParser = require('body-parser');
var mysql = require("mysql");
var renman = require('node-jt400');

When the code shows the error, it's pointing to the line var app = express();.  However if I comment out the var renman = require('node-jt400'); line the program works without issue.  Am I possible missing something on my machine?

For reference I'm using 5.1.0.0 of Node the above issue.

I down graded to node 4.2.3.0, and now when I run in debug mode with the require not commented out, I get the following error:

Error: Module version mismatch. Expected 46, got 47.

The debugger stops in a module.js file (not sure if that's part of node or node-jt400).

**Comment by bergur** [comment]
Hi geoffreywk.

This is a late reply but can hopefully help you.

Error: Module version mismatch. Expected 46, got 47 usually comes up in the following scenario:

1. You set up / install nodejs on  your computer
2. You create your program and do npm install (so all modules are installed)
3. You update nodejs on your computer.

Basically you installed all the packages with one version number and then you're trying to run it using another.

Try removing node_modules folder completely and then run npm install again.

**Comment by bergur** [comment]
Hi @geoffreywk we're closing the issue but feel free to reopen.
