### ISSUE TITLE
Possible to set connection as Read-Only?

### ISSUE THREAD

**Issue by Mattperkinsee** [tryggingamidstodin/node-jt400#53]
Is this possible when you create the connection? The data I'm connecting to is used on a daily basis, and it would be nice if you could set the connection to be read-only.

**Comment by cwg999** [comment]
There appears to be no read-only connection option. Your best bet is to create a read-only user on the database and use that. 

the supported connection config properties are here, for JT400:
https://www.ibm.com/support/knowledgecenter/en/ssw_ibm_i_73/rzahh/javadoc/com/ibm/as400/access/doc-files/JDBCProperties.html

**Comment by bergur** [comment]
Hi @Mattperkinsee 

To piggyback-ride on Cody's answer. The node-jt400 module just passes on the config object as it comes. So you should be able to use any property that the openjt400 java library accepts, including the access parameter.

In your code where you put in the host, user and password, try to add the access property as suggested by cody.

const config = {
