### ISSUE TITLE
Call program -> Error running instance method

### ISSUE THREAD

**Issue by semasdev** [tryggingamidstodin/node-jt400#54]
Hello,
i got this PHP code which calls a program (and works still fine):

```
$sql = "call reppgm.rkm0125('12', '34', '123456', '78', 'ABCDEF', 'RAUE102', '', '', '')";
$this->db->execQuery($sql);
```
and i tried to translate it to a node-jt400 program:
		
```
const myProgram = pool.defineProgram({ 
programName: "RKM0125",
paramsSchema: [
  {type: "CHAR", precision: 2, scale: 0, name: "Firma"},
  {type: "CHAR", precision: 2,  scale: 0, name: "Filiale"},
  {type: "CHAR", precision: 6, scale: 0, name: "AuftragNr"},
  {type: "CHAR", precision: 2, scale: 0, name: "AuftragFg"},
  {type: "CHAR", precision: 6, scale: 0, name: "Herkunft"},
  {type: "CHAR", precision: 10, scale: 0, name: "Programmname"},
  {type: "CHAR", precision: 6, scale: 0, name: "ReturnCode"},
  {type: "CHAR", precision: 50, scale: 0, name: "ReturnText"},
  {type: "CHAR", precision: 10, scale: 0, name: "User"},
],
  libraryName: "REPPGM",
});
                                    
myProgram({
Firma: "12",
Filiale: "34",
AuftragNr: "123456",
AuftragFg: "78",
Herkunft: "ABCDEF",
Programmname: "RAUE102",
ReturnCode: "",
ReturnText: "",
User: "",
})
.then((result) => {
[...]
})
.catch((err) => {
[...]
});
```

But all i get is this error:
```
[Error: Error running instance method
com.ibm.as400.access.ConnectionDroppedException: Connection was dropped unexpectedly.
        at com.ibm.as400.access.ClientAccessDataStream.construct(ClientAccessDataStream.java:62)
        at com.ibm.as400.access.AS400ThreadedServer.run(AS400ThreadedServer.java:357)
        at java.lang.Thread.run(Thread.java:748)
] {
  cause: nodeJava_com_ibm_as400_access_ConnectionDroppedException {}
}
```

if i set the timeout to 0, no answer is returned, multiple normal queries are working before and after

**Comment by bergur** [comment]
Hi @semasdev 

The error: Connection was dropped unexpectedly is from jt400 and means that timeout limit is kicking in. It defaults to 3 sec. Basically it can't run your code in 3 seconds, so it terminates and returns this message.

Putting timeout to 0 sec means there is no limit. In that case there are two possibilities:
a) You get an answer from your AS400 machine after some time.
b) The AS400 can't process your requests and never returns any results

Scenario b is what is happening to you. Do you have direct access to the AS400 machine? What happens if you run the RKM0125 program with the same paramters you are sending in?

Are you sure that the program definition is correct? Is everything defined as char in your AS400 program?

**Comment by semasdev** [comment]
Hi @bergur ,
thanks for your fast reply. 

No, i'm not sure about my definitions , only about the lengths. I took 'CHAR' because of the empty 'string' fields of the PHP parameters. Are there other possible data types (with that php snippet in mind)? Is CHAR here different to VARCHAR?

I'll try running the program directly later, my AS400 is not available for the next 5 hours.

**Comment by bergur** [comment]
Regarding the definitions, they have match your programs definitions. so when you can check your AS400, check the parameters.

The Decimal type maps to com.ibm.as400.access.AS400PackedDecimal The Numeric type maps to com.ibm.as400.access.AS400ZonedDecimal Everything else (char) maps to com.ibm.as400.access.AS400Text Precision is the size and scale is the decimals.

**Comment by semasdev** [comment]
Calling the Program directly on the AS400 works as expected, no problems at all...

i also tried to run it as a query 
`pool.query("CALL reppgm.rkm0125('12', '34', '123456', '78', 'ABCDEF', 'RAUE102', '', '', '')") `

which works...! But gives me a 'Cursor state not valid' error...

**Comment by bergur** [comment]
I understand.

I'm afraid I don't have any concrete answer for you. Normally when programs halts in node-jt400 its usually the wrong types of parameters, usually the logs on the AS400 can help.

I know the program worked on the AS400 machine, but have you checked the definition of your program to make sure they match the defineProgram paramters?

I didn't now insertAndGetId worked with call statements, good to know. Thanks :)

**Comment by bergur** [comment]
Hey @semasdev did you ever find out what was the problem? Is this working now?

Best regards
Bergur

**Comment by semasdev** [comment]
hey @bergur, no sorry. Didn't have the time to dig deeper. But it still works quite well:
`pool.insertAndGetId("CALL reppgm.rkm0125('12', '34, '56', '79', 'ABCDEF', 'RAUE102', '', '', '')")`

Also, im quite thankfull for your code, it powers a large part of our internal dataflow. Sadly, within the next 5 years we will move away from the IBM System i Platform.
