### ISSUE TITLE
Possible Batch Update - using UPDATE STATEMENT

### ISSUE THREAD

**Issue by dc-deal** [tryggingamidstodin/node-jt400#56]
Hello, is it possible to launch a "batchUpdate", with UPDATE Statements instead of INSERT'S (Like shown in the Examples)
Goal: Performance, not having to run all updates sequencially.

An example for that:
```
const data = [
    [1, 'a'],
    [2, 'b']
];

pool
  .batchUpdate('UPDATE FOO SET FIELD1 = ? WHERE FIELD2=  ?)', data)
  .then(result => {
    console.log(result);
});
```
To Make it even more clear - the example shown above would commit two SQL UPDATE STATEMENTS:
```
UPDATE FOO SET FIELD1 = 1 WHERE FIELD2 = 'a'
UPDATE FOO SET FIELD1 = 2 WHERE FIELD2 = 'b'
```

**Comment by bergur** [comment]
HI @dc-deal 

Making such is possible, but it would just a syntactic sugar on opening a transaction, sending an update statement to the server, waiting for response, sending the next update statement, waiting for a response, then finally commiting the transaction. That isn't very robust.

I would reccomend taking a look at `update from values.`

Something like

```javascript

const sql = `UPDATE foo as f SET
    field1 = t.field1
FROM (VALUES
    (1, 'a'),
    (2, 'b')  
) as  t (field1, field2) 
where c.field2 = t.field2`

pool.update(sql)
```

Should do the trick.

**Comment by dc-deal** [comment]
Hey, thanks for the quick response there! 

I See your SQL knowledge far outrages mine, i m trying to understand this. Can you give me another example for this kind of - more complex - constellation:

```
The Table "FOO"
Primary-Keys: "DATE1", "ARGUMENT1"
Write-Fields shall be: "TEXT1"

| DATE1      | ARGUMENT1 | TEXT1 |
|------------|-----------|-------|
| 2020-09-07 | 1         | null  |
| 2020-09-07 | 2         | null  |
| 2020-09-08 | 1         | null  |
| 2020-09-08 | 2         | null  |
| 2020-09-09 | 1         | null  |
```

Now, i want to update my Table, say, I want to touch 3 rows. Those UPDATES would look like:

```
UPDATE FOO SET TEXT1 = 't01' where DATE1 = '2020-09-07' and ARGUMENT1 = 1;
UPDATE FOO SET TEXT1 = 'tx' where DATE1 = '2020-09-08' and ARGUMENT1 = 2;
UPDATE FOO SET TEXT1 = 'ty' where DATE1 = '2020-09-09' and ARGUMENT1 = 1;
```

Expected Result on "FOO"
```
| DATE1      | ARGUMENT1 | TEXT1 |
|------------|-----------|-------|
| 2020-09-07 | 1         | t01   |
| 2020-09-07 | 2         | null  |
| 2020-09-08 | 1         | null  |
| 2020-09-08 | 2         | tx     |
| 2020-09-09 | 1         | ty     |
```

My current way to do this would be: 
```
    const array = [
        ['t01', '2020-09-07', 1],
        ['tx', '2020-09-08', 2],
        ['ty', '2020-09-09', 1],
    ];
    for (let i = 0; i < array.length; i++) {
        await pool.update(
            'UPDATE FOO SET TEXT1 = ? where DATE1 = ? and ARGUMENT1 = ?',
            array[i]
        );
    }

```
Unfortunately, this is tribbly slow, especcially when you have to update Data of thousands in such a KEY / VALUE pair manner.

**Comment by bergur** [comment]
Hi @dc-deal 

Yeah I can take a look at this. Right this moment though I'm using my vacation trying to work on the garden/house, but I will answer you later tonight when I'm back in front of the computer.

**Comment by bergur** [comment]
Ok so long answer:

pool.batchUpdate works only for inserts because SQL inserts work for multiple rows,

```
insert into users (name, sex) values ('bergur', 1), ('franky', 1)
```

Update works for multiple rows but only for the same criteria.
``
update users set sex = 1 where name = 'bergur'
```

As soon as you want to update multiple rows in single query for different critery it becomes a little more tricky. This hold true for any database and/or module. But there are few solutions.

1) Loop through the update statements (like you are doing). This can be time consuming since you are sending multiple requests to the db, which, locks, updates and commits and sends the response.

2) Use insert and use feature like 'on duplicate update' or 'merge'
See for example this answer on SO: https://stackoverflow.com/questions/20402529/db2-iseries-insert-on-duplicate-key

3) Use update from values, it creates a temporary value table and updates according to it.
'm not sure if DB2 supports it, but worth the shot.

Instead of 

```
UPDATE FOO SET TEXT1 = ? where DATE1 = ? and ARGUMENT1 = ?',
```

It would become
```
const sql = `
UPDATE foo as f SET
    f.text1 = t.text1
FROM (VALUES
    ('t01', '2020-09-07', 1),
    ('tx', '2020-09-08', 2),
    ('ty', '2020-09-09', 1)
) as t (text1, date1, argument1) 
where f.date1 = t.date1`
and f.argument1 = t.argument1

pool.update(sql)
```

Here you are updating foo and setting text1 in foo equal to  text1 in your temp table (t) where date and argument match.

I'm not 100% sure it works for db2, but worth checking out.

**Comment by dc-deal** [comment]
Thanks a Lot! Got it done now!! 

The way I Do it (tested! - Field names altered for Example):
```js
   try {
        // get "Array of Array" from "Array of Object".
        const data = allDataObj.map(i => [
            i.field1,
            i.field2,
            i.field3,
            i.whereField1,
            i.whereField2
        ]);
        const sql =
            ' MERGE INTO ' +
            'FOOTAB ' +
            ' AS T' +
            ' USING (VALUES( ' +
            'CAST(? as DECIMAL(4,2)),' +
            'CAST(? as DECIMAL(15,6)),' +
            'CAST(? as DECIMAL(15,6))' +
            ' )) AS DAT(FIELD1, FIELD2, FIELD3)' +
            ' ON  WHEREFIELD1= ? and  WHEREFIELD2= ?' +
            ' WHEN MATCHED THEN UPDATE ' +
            ' set ' +
            ' T.FIELD1T = DAT.FIELD1,' +
            ' T.FIELD2T = DAT.FIELD2,' +
            ' T.FIELD3T = DAT.FIELD3,' +
            " T.FIELD4T = 'comment'";
        await db2Pool.batchUpdate(sql, data).then(result => {
            console.log(result);
        });
    } catch (err) {
        console.log(err);
    }
```
**MIND THE CAST'S!!!! 
It is vital to CAST(), unless you get a "SQL0584", just don't ask why - i don't know why this is so strict right here.**

Additional possibilities are, if the WHEN-CLAUSE would not match , you can additonaly insert the record (i didn't need this here)

performance is perfect with this.

**Comment by bergur** [comment]
Glad to hear its working and thanks for posting the solution.

I don't think we will be adding this to the documentation since this is just normal SQL and is more related to the database itself (DB2) rather than the module. But I'll let the team know of this, and we'll talk it out.

Good luck with your program.
