### ISSUE TITLE
is there a way to increase the highWaterMark on createReadStream method?

### ISSUE THREAD

**Issue by gorydev** [tryggingamidstodin/node-jt400#57]
Hello, I'm trying to pass this option on `createReadStream` method but I'm getting an error, this is my code: 
`const readStream = pool.createReadStream(query, { highWaterMark: 32768 });`

and this is the error: 
`TypeError: (params || []).map is not a function
    at paramsToJson (/app/node_modules/node-jt400/dist/lib/jt400.js:95:42)
    at Object.obj.createReadStream (/app/node_modules/node-jt400/dist/lib/jt400.js:105:32)` 
I'm not sure if there's something wrong with my code or how can I increase this highWaterMark since the default value = 16384 is not enough for my?

**Comment by OlafurTorfi** [comment]
The second parameter you send in should be an array, with values to be substituted for questionmarks in the query string.

maybe something like this 
`pool.createReadStream('select * from waterLevel where highWaterMark=?', [32768])`

**Comment by bergur** [comment]
Hi @gorydev 

As @OlafurTorfi mentions, the second argument to query is the parameters, not the options for the stream.

Currently there is no way to set highWatermark for the stream, but you can check out following code if you wanna have a crack at it. 

Java
https://github.com/tryggingamidstodin/node-jt400/blob/master/java/src/nodejt400/JT400.java#L48
https://github.com/tryggingamidstodin/node-jt400/blob/master/java/src/nodejt400/JdbcJsonClient.java#L66
https://github.com/tryggingamidstodin/node-jt400/blob/master/java/src/nodejt400/ResultStream.java

Node
https://github.com/tryggingamidstodin/node-jt400/blob/master/lib/jt400.ts#L144
https://github.com/tryggingamidstodin/node-jt400/blob/master/lib/jdbcstream.ts
