### ISSUE TITLE
[QUESTION] pool.query lose data types

### ISSUE THREAD

**Issue by Alastyr** [tryggingamidstodin/node-jt400#63]
Hi,
executing query with pool.query returns an object with all values as string:
```
{
     id: "1",
     username: "alastyr",
     age: "99"
}
```
Is there any way to return an object without losing database data type? Like this:
```
{
     id: 1,
     username: "alastyr",
     age: 99
}
```

Thank you

**Comment by bergur** [comment]
Hi @Alastyr 

Currently, this is not doable. It is possible to change the module to know and return data types. Unfortunately we don't have the time nor manpower to change this.

My recommendation would just to map out like this.

```javascript
pool.query(sql, params).then(res => {
  return res.map(item => ({
    id: Number(res.ID),
    username: res.USERNAME,
    age: Number(res.AGE)    
  }))
})
```

You could also move this to a funciton

```
const mapToUser = (item) => ({
  id: Number(res.ID),
  username: res.USERNAME,
  age: Number(res.AGE)    
}))

pool.query(sql, params).then(res => res.map(mapToUser)
```

Or make the function do the mapping

```
const mapToUser = (list) => {
  return list.map(item => ({
    id: Number(res.ID),
    username: res.USERNAME,
    age: Number(res.AGE)        
  })
}

pool.query(sql, params).then(mapToUser)
```

**Comment by Alastyr** [comment]
Hi, thank you for your reply!
