### ISSUE TITLE
How to check for Server Response Errors and Exceptions?

### ISSUE THREAD

**Issue by sumitridhal** [tryggingamidstodin/node-jt400#7]
I'm executing some complex queries and getting query string with params [], what i'm expecting is Database Exception Response in return.

`SELECT * FROM .... params: []`

How to check for Error or Response from Server for Exceptions

**Comment by bergur** [comment]
Try something like 

`db.query(sqlString,params).then(function(res) {
  console.log(res);
}).fail(function(err) {
  console.log(err);
});`

**Comment by sumitridhal** [comment]
Hi @bergur Bergur Hallgrimsson,
Thank you for looking into this.
solution is definitely the way to go.
Thanks
