### ISSUE TITLE
Possible to do prepared batchUpdate with Merge Into

### ISSUE THREAD

**Issue by Mattperkinsee** [tryggingamidstodin/node-jt400#71]
In order to perform a MYSQL "On duplicate Key" in DB2, I do something like this

```
MERGE INTO TEST AS T
USING (VALUES( 1, 9,  9))  AS DAT(A, B,  C)
ON T.A = DAT.A 
WHEN MATCHED THEN UPDATE  SET T.C = DAT.C
WHEN NOT MATCHED THEN  INSERT (A, B,  C)  VALUES (DAT.A, DAT.B, DAT.C)
```

Is it possible to perform this using a prepared statement with batchUpdate with something like 

```
pool
  .batchUpdate(`
    MERGE INTO TEST AS T
    USING (VALUES( ?, ?, ?))  AS DAT(A, B,  C)
    ON T.A = DAT.A 
    WHEN MATCHED THEN UPDATE  SET T.C = DAT.C
    WHEN NOT MATCHED THEN  INSERT (A, B,  C)  VALUES (DAT.A, DAT.B, DAT.C)`, data)
  .then(result => {
    console.log(result);
});

where data looks like 
const data = [
    [1, 'a', 'c'],
    [2, 'b', 'c']
];

```

I keep running into [SQL0158] Number of columns specified not consistent. I'm sure I could run it by building a string instead of doing a prepared statement, but ya know..SQL injection and all that jazz.

Thanks.

**Comment by Mattperkinsee** [comment]
I believe this is possible. For some reason I am having issues using this merge statement even though I have done so in the past. I wonder if the merge requires me to specify all columns as I'm not updating all the columns in the table.  I'm able to get this working by doing a merge statement by doing this. This is still string building, but I might be able to convert it over to prepared successfully now.


```
MERGE INTO AS400_Table AS mt USING (
                        SELECT * FROM TABLE (
                            VALUES 
                                ${values}
                        )
                    ) AS vt(id_col1, col2, col3) 
                    ON (mt.id_col1 = vt.id_col1) 
                    WHEN NOT MATCHED THEN
                        INSERT (id_col1,col2,col3) 
                    VALUES (vt.id_col1, vt.col2, vt.col3)
                    ELSE IGNORE`
```

**Comment by jakobrun** [comment]
When I use a merge statement I have to specify the types of the parameters in the statement. Something like this:
```
MERGE INTO TEST AS T
USING (VALUES( cast(? as INT), cast(? as INT), cast(? as INT)))  AS DAT(A, B,  C)
ON T.A = DAT.A 
WHEN MATCHED THEN UPDATE  SET T.C = DAT.C
WHEN NOT MATCHED THEN  INSERT (A, B,  C)  VALUES (DAT.A, DAT.B, DAT.C)`, data)
```
I haven't tried it with a batch update though.
