### ISSUE TITLE
ifs getdirectory

### ISSUE THREAD

**Issue by dbouchierarcad** [tryggingamidstodin/node-jt400#72]
Hello,

i use this module in a project, and i'm not a java developper. 
 Is There an easy way to add the method jt400 getdirectory on the pool.ifs() .
Today i use a query select on table ifs_object_statistics db2, but this table are not available on IBMi V7R1 (the version of customer). 

I need to get dynamicly the file in folder with subdirectory (i know only the name of files but not the directory).

Sorry for my English (i'm french)

thanks

**Comment by OlafurTorfi** [comment]
Easy is a relative term :)

Feel free to experiment, and once you have it working. We will review your pull request.

At the moment Tryggingarmidstodin is not putting resources into developing features it does not need.
