### ISSUE TITLE
Working with Docker

### ISSUE THREAD

**Issue by woodinteractive** [tryggingamidstodin/node-jt400#73]
Do you know if this can be used with Docker? If so, do you know how to structure the dockerfile with openjdk?

**Comment by bergur** [comment]
Yes this can be used in docker. Tryggingamidstodin is running everything in docker.
Here is an example of java-jdk for alpine: https://hub.docker.com/layers/openjdk/library/openjdk/8-jdk-alpine/images/sha256-210ecd2595991799526a62a7099718b149e3bbefdb49764cc2a450048e0dd4c0?context=explore

**Comment by woodinteractive** [comment]
> Yes this can be used in docker. Tryggingamidstodin is running everything in docker. Here is an example of java-jdk for alpine: https://hub.docker.com/layers/openjdk/library/openjdk/8-jdk-alpine/images/sha256-210ecd2595991799526a62a7099718b149e3bbefdb49764cc2a450048e0dd4c0?context=explore

Do you have an example of a Dockerfile? I keep getting errors when installing the node_modules—specifically related to node-gyp.

**Comment by woodinteractive** [comment]
What I wound up doing is creating a multiple stage container using centos 8 as a build and installed everything as normal, then I copied my application directory from that stage to next using openjdk:11 and installed node v14.x on it. Everything worked perfectly.

**Comment by Clauber** [comment]
I know this a bit old, but I managed to create a dockerfile and would like to share in case anyone(including me, of course lol) needs that in the future
It is using openjdk 11 and node 14

```
FROM openjdk:11

# Install python, make, g++, and nodejs(in order for the node app and node-jt400 to work)
RUN curl -sL https://deb.nodesource.com/setup_14.x | bash - \
    && apt-get update -qq \
    && apt-get install -qq  \
    python \
    make \
    g++ \
    nodejs \
    && apt-get upgrade -qq \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 3000

CMD ["npm", "run", "start"]
```bash
