### ISSUE TITLE
async  2.0.0 - 2.6.3 Vulnerability 

### ISSUE THREAD

**Issue by Mattperkinsee** [tryggingamidstodin/node-jt400#76]
I'm not sure why it would try installing node-jt400@1.1.3? Any ideas what is happening here?

async  2.0.0 - 2.6.3
Severity: high
Prototype Pollution in async - https://github.com/advisories/GHSA-fwr7-v2mv-hh25
fix available via `npm audit fix --force`
Will install node-jt400@1.1.3, which is a breaking change
node_modules/async
  java  0.8.0 - 0.12.2
  Depends on vulnerable versions of async
  node_modules/java
    node-jt400  >=1.2.0
    Depends on vulnerable versions of java
    node_modules/node-jt400

3 high severity vulnerabilities

**Comment by woodinteractive** [comment]
I'm seeing the same. Looks like this was originally posted over a month ago. Some comment would be wonderful.

**Comment by bergur** [comment]
Hey

When is this happening? At npm install? What version of node-jt400 are you running?

**Comment by Mattperkinsee** [comment]
node-jt400 version 4.4.0. Yes, at npm install. I think it might be due to the java 0.12.2 dependency and that java requires async 2.6.1. I'm trying to update it to 2.6.4, but it keeps installing 2.6.1.

**Comment by Mattperkinsee** [comment]
I was able to resolve this by adding to my package.json 

"overrides": {
    "async": "2.6.4"
  }
