### ISSUE TITLE
[QUESTION] InMemory DB Documentation

### ISSUE THREAD

**Issue by kansasturnpike** [tryggingamidstodin/node-jt400#79]
Is there any documentation on how to use `InMemoryDb()`? I can't figure out how to use if for testing. Any help would be appreciated.

**Comment by OlafurTorfi** [comment]
It should work exactly like a connection created with `pool()`. And inject it into your functions instead of a real connection for testing.
But just after creating the InMemoryDb(), there are no tables in your database. You need to create them yourself...
