### ISSUE TITLE
.then() code not processed

### ISSUE THREAD

**Issue by Duraimurugan** [tryggingamidstodin/node-jt400#8]
@tryggingamidstodin 
I am trying to implement node-jt400 in my code, I am able to make a connection and get the response for a SELECT query, the response is automatically logged in the console. But I dont see the compiler/flow been moved to the .then() block. Here is my code, 

_pool.query('SELECT ARDTGI, FNAMGI FROM SOMETHING/NIP  WHERE KYDTGI = ? and SEQGI = ?', [42703, 2342312])
    .then(function (err, result) {
      if(err) { console.log(err); }
      else { console.log('RESULT here:   ' + result); }
    });_

the code inside then() block is not getting called. Am is missing something or this is an issue with the library?

 @jakobrun @pshomov

**Comment by bergur** [comment]
Hi Duraimurugan, my name is Bergur and I work at Tryggingamidstodin.

The module logs out the sql if there's an error running the sql. My best guess would be that there's something wrong with the sql. Have you tried it in a SQL program like SQL workbench?

Also, the promise (then) only returns results not errors.

pool.query('SELECT ARDTGI, FNAMGI FROM SOMETHING/NIP WHERE KYDTGI = ? and SEQGI = ?', [42703, 2342312])
.then(function (result) {
 console.log('works');
 console.log(result);
}).fail(function (error) {
 console.log('fails');
console.log(error);
});

**Comment by Duraimurugan** [comment]
Its my bad. By the time I figured out the incorrect piece of code, you have replied. Thank you for responding quickly. kindly close the issue.
Also, do you any samples which I can refer for making stored procedures calls from nodejs to AS400 through node-jt400?

**Comment by bergur** [comment]
Yeah its missing in our readme, but you can use

```javascript
var myProgram pool.pgm('nameOfProgram', [
 {type: 'CHAR', precision: 32, scale: 0, name: 'ID'},
 {type: 'NUMERIC', precision: 12, scale: 2, name: 'Total'},
]);
```
and then call it like this:

```javascript
myProgram({
ID: '5731570AA9824074B3DB0A25EE6CC7F1',
Sum: 2000
})..then(function (result) {
 console.log('works');
 console.log(result);
}).fail(function (error) {
 console.log('fails');
console.log(error);
});
```
